# Generated by Django 5.2.8 on 2025-11-20 15:21

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='posts/images/'),
        ),
    ]
