# Generated by Django 5.2.8 on 2025-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_first_name_customuser_last_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_ab560e_idx'),
        ),
    ]
