# Generated by Django 5.2.8 on 2025-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_accounts_cu_usernam_ab560e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile/'),
        ),
    ]
